force-app/main/default/objects/Quote/fields/Client_Country__c.field-meta.xml
<CustomField>
    <fullName>Client_Country__c</fullName>
    <description>Stores a two-digit EU сlient country code</description>
    <inlineHelpText>Provide a 2 digit EU country code</inlineHelpText>
    <label>Client Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BG</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>CY</fullName>
            </value>
            <value>
                <fullName>CZ</fullName>
            </value>
            <value>
                <fullName>DK</fullName>
            </value>
            <value>
                <fullName>EE</fullName>
            </value>
            <value>
                <fullName>FI</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>GR</fullName>
            </value>
            <value>
                <fullName>HU</fullName>
            </value>
            <value>
                <fullName>IE</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>LV</fullName>
            </value>
            <value>
                <fullName>LT</fullName>
            </value>
            <value>
                <fullName>LU</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NL</fullName>
            </value>
            <value>
                <fullName>PL</fullName>
            </value>
            <value>
                <fullName>PT</fullName>
            </value>
            <value>
                <fullName>RO</fullName>
            </value>
            <value>
                <fullName>SK</fullName>
            </value>
            <value>
                <fullName>SI</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>GB</fullName>
            </value>
            <value>
                <fullName>XI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/VAT_Rate__c.field-meta.xml
<CustomField>
    <fullName>VAT_Rate__c</fullName>
    <label>VAT Rate</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PresentVatDataController.cls
public with sharing class PresentVatDataController  {

	@AuraEnabled
	public static VatService.VatWrapper getVatData(String quoteId) {
		Quote q = [SELECT Id, Client_Country__c FROM Quote WHERE Id =: quoteId LIMIT 1];

		Map<String, VatService.VatWrapper> vatWrappersByStrings = new VatService().getVAT();

		if (vatWrappersByStrings.containsKey(q.Client_Country__c)) {
			return vatWrappersByStrings.get(q.Client_Country__c);
		}

		return null;
	}

	@AuraEnabled
	public static void updateVatData(String quoteId) {
		Quote quoteToUpdate = [SELECT Id, Client_Country__c, VAT_Rate__c FROM Quote WHERE Id =: quoteId LIMIT 1];

		VatService.VatWrapper wrapper = getVatData(quoteId);

		if(wrapper != null){
			quoteToUpdate.VAT_Rate__c = wrapper.standard;
			update quoteToUpdate;
		}
	}


}