force-app/main/default/objects/Quote/fields/Client_Country__c.field-meta.xml
<CustomField>
    <fullName>Client_Country__c</fullName>
    <description>Stores a two-digit EU сlient country code</description>
    <inlineHelpText>Provide a 2 digit EU country code</inlineHelpText>
    <label>Client Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BG</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>CY</fullName>
            </value>
            <value>
                <fullName>CZ</fullName>
            </value>
            <value>
                <fullName>DK</fullName>
            </value>
            <value>
                <fullName>EE</fullName>
            </value>
            <value>
                <fullName>FI</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>GR</fullName>
            </value>
            <value>
                <fullName>HU</fullName>
            </value>
            <value>
                <fullName>IE</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>LV</fullName>
            </value>
            <value>
                <fullName>LT</fullName>
            </value>
            <value>
                <fullName>LU</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NL</fullName>
            </value>
            <value>
                <fullName>PL</fullName>
            </value>
            <value>
                <fullName>PT</fullName>
            </value>
            <value>
                <fullName>RO</fullName>
            </value>
            <value>
                <fullName>SK</fullName>
            </value>
            <value>
                <fullName>SI</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>GB</fullName>
            </value>
            <value>
                <fullName>XI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/VAT_Rate__c.field-meta.xml
<CustomField>
    <fullName>VAT_Rate__c</fullName>
    <label>VAT Rate</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PresentVatDataControllerTest.cls
@IsTest
private class PresentVatDataControllerTest {

	@TestSetup
	public static void setupTestData() {
		Account testAccount = TestDataFactory.createAccount();
		insert testAccount;

		Opportunity testOpportunity = TestDataFactory.createOpportunity();
		testOpportunity.AccountId = testAccount.Id;
		insert testOpportunity;

		API__c myCustomSetting = TestDataFactory.createApi();
		insert myCustomSetting;
	}

	@IsTest
	static void testGetVatData() {
		Test.setMock(HttpCalloutMock.class, new MockHandler(TestDataFactory.RESPONSE_JSON, 200));

		Quote testQuote = TestDataFactory.createQuote();
		testQuote.OpportunityId = [SELECT Id FROM Opportunity LIMIT 1].Id;
		insert testQuote;

		Test.startTest();
		VatService.VatWrapper result = PresentVatDataController.getVatData(testQuote.Id);
		Test.stopTest();

		Assert.areNotEqual(null, result);
		Assert.areEqual(20, result.standard);
	}

	@IsTest
	static void testNoDataFound() {
		Test.setMock(HttpCalloutMock.class, new MockHandler(TestDataFactory.RESPONSE_JSON, 200));

		Quote testQuote = TestDataFactory.createQuote();
		testQuote.OpportunityId = [SELECT Id FROM Opportunity LIMIT 1].Id;
		testQuote.Client_Country__c = 'BG';
		insert testQuote;

		Test.startTest();
		VatService.VatWrapper result = PresentVatDataController.getVatData(testQuote.Id);
		Test.stopTest();

		Assert.areNotEqual(testQuote.VAT_Rate__c, result.standard);
		Assert.areEqual(0, result.standard);
	}

	@IsTest
	static void testUpdateVatData() {
		Test.setMock(HttpCalloutMock.class, new MockHandler(TestDataFactory.RESPONSE_JSON, 200));

		Quote testQuote = TestDataFactory.createQuote();
		testQuote.OpportunityId = [SELECT Id FROM Opportunity LIMIT 1].Id;
		testQuote.VAT_Rate__c = 11;
		insert testQuote;

		Test.startTest();
		PresentVatDataController.updateVatData(testQuote.Id);
		Test.stopTest();

		Quote updatedQuote = [SELECT VAT_Rate__c FROM Quote WHERE Id = :testQuote.Id LIMIT 1];

		Assert.areNotEqual(11, updatedQuote.VAT_Rate__c);
		Assert.areEqual(20, updatedQuote.VAT_Rate__c);
	}

}